#line 2 "expr-scanner.c"

#line 4 "expr-scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer pdl__create_buffer
#define yy_delete_buffer pdl__delete_buffer
#define yy_flex_debug pdl__flex_debug
#define yy_init_buffer pdl__init_buffer
#define yy_flush_buffer pdl__flush_buffer
#define yy_load_buffer_state pdl__load_buffer_state
#define yy_switch_to_buffer pdl__switch_to_buffer
#define yyin pdl_in
#define yyleng pdl_leng
#define yylex pdl_lex
#define yylineno pdl_lineno
#define yyout pdl_out
#define yyrestart pdl_restart
#define yytext pdl_text
#define yywrap pdl_wrap
#define yyalloc pdl_alloc
#define yyrealloc pdl_realloc
#define yyfree pdl_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE pdl_restart(pdl_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t pdl_leng;

extern FILE *pdl_in, *pdl_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pdl_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up pdl_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via pdl_restart()), so that the user can continue scanning by
	 * just pointing pdl_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when pdl_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t pdl_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow pdl_wrap()'s to do buffer switches
 * instead of setting up a fresh pdl_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void pdl_restart (FILE *input_file  );
void pdl__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE pdl__create_buffer (FILE *file,int size  );
void pdl__delete_buffer (YY_BUFFER_STATE b  );
void pdl__flush_buffer (YY_BUFFER_STATE b  );
void pdl_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void pdl_pop_buffer_state (void );

static void pdl_ensure_buffer_stack (void );
static void pdl__load_buffer_state (void );
static void pdl__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER pdl__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE pdl__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE pdl__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE pdl__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *pdl_alloc (yy_size_t  );
void *pdl_realloc (void *,yy_size_t  );
void pdl_free (void *  );

#define yy_new_buffer pdl__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        pdl_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pdl__create_buffer(pdl_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        pdl_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pdl__create_buffer(pdl_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *pdl_in = (FILE *) 0, *pdl_out = (FILE *) 0;

typedef int yy_state_type;

extern int pdl_lineno;

int pdl_lineno = 1;

extern char *pdl_text;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr pdl_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up pdl_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	pdl_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 47
#define YY_END_OF_BUFFER 48
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[191] =
    {   0,
        0,    0,   48,   46,   45,   45,   46,   46,   46,   46,
       46,   44,    3,    1,   43,    2,   32,   32,   46,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   42,   10,   37,   35,   40,
       29,    0,   41,    0,   32,   38,   38,   38,    9,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   11,   12,
       38,   38,   38,   13,   14,   38,   38,   16,   38,   38,
        0,   39,   34,   33,   15,   38,   38,   38,   38,   38,
       38,    4,   38,   38,   38,   38,   38,    5,   17,   38,
       38,   36,   38,   38,   38,   38,   38,   38,   38,   38,

       38,   38,   38,   30,   38,   38,   38,   38,   38,   38,
       38,   38,   28,   38,   31,   38,   38,   38,   38,   38,
       38,   38,    7,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,    6,    8,   19,   38,   38,   38,   38,
       38,   20,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   21,   38,   38,   38,   38,   22,   24,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   18,   38,   23,   38,
       38,   38,   38,   25,   38,   38,   26,   38,   27,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    6,    7,    1,    8,    9,
        9,   10,   11,   12,   13,   14,    1,   15,   16,   17,
       18,   18,   18,   18,   18,   18,   18,    9,    1,    1,
       19,    1,    1,    1,   20,   20,   20,   20,   20,   20,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
        9,    1,    9,    1,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   21,   31,   32,   33,   34,
       35,   36,   21,   37,   38,   39,   40,   41,   42,   43,
       44,   21,    1,    1,   45,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[46] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    3,    3,    3,    3,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1
    } ;

static yyconst flex_uint16_t yy_base[198] =
    {   0,
        0,    0,  391,  392,  392,  392,  371,    0,    0,   24,
      381,  392,  392,  392,  392,  392,   50,   60,  369,  373,
       46,   39,   33,   56,   38,   35,   57,   73,   71,   74,
       37,   75,   77,   78,   76,  392,  392,    0,  372,    0,
        0,  377,  392,    0,  102,  370,   83,  107,  392,  112,
       80,   89,  121,  124,   88,  122,  125,  126,  369,  368,
      127,  128,  130,  367,  366,  129,  131,  365,  133,  135,
        0,  364,   92,    0,  363,  138,  137,   41,  141,  145,
      142,  362,  139,  143,  147,  157,  158,  361,  360,  163,
      164,    0,  166,  169,  170,  173,  174,  178,  176,  183,

      179,  185,  188,  359,  180,  193,  197,  198,  199,  201,
      202,  207,  358,  203,  357,  206,  208,  209,  211,  210,
      216,  212,  356,  218,  230,  220,  224,  228,  231,  235,
      238,  236,  232,  355,  354,  353,  240,  241,  242,  249,
      246,  346,  251,  255,  256,  257,  258,  262,  259,  264,
      265,  267,  345,  268,  269,  272,  274,  344,  343,  275,
      283,  277,  286,  285,  287,  289,  293,  291,  299,  295,
      300,  302,  310,  306,  296,  322,  341,  323,  340,  325,
      303,  309,  328,  339,  324,  329,  338,  330,  335,  392,
      342,  316,  159,  361,  363,   98,   53

    } ;

static yyconst flex_int16_t yy_def[198] =
    {   0,
      190,    1,  190,  190,  190,  190,  190,  191,  192,  193,
      194,  190,  190,  190,  190,  190,  195,  195,  190,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  190,  190,  191,  192,  193,
      193,  194,  190,  196,  195,  195,  195,  195,  190,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      197,  196,  195,   48,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  197,  195,  195,  195,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,    0,
      190,  190,  190,  190,  190,  190,  190

    } ;

static yyconst flex_uint16_t yy_nxt[438] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,    4,   17,   18,   18,   18,   19,   20,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       20,   30,   31,   32,   33,   20,   20,   20,   34,   35,
       20,   20,   20,   20,   36,   41,   44,   41,   44,   41,
       44,   44,   44,   41,   44,   92,   58,   95,   41,   44,
       41,   54,   41,   44,   45,   45,   45,   45,   52,   44,
       44,   66,   47,   44,   45,   45,   45,   45,   53,   50,
       57,   55,   59,   51,   44,   56,   44,   44,   44,   44,
       44,   44,   48,   44,   61,   60,   44,   73,   73,   64,

       72,   44,   44,   76,   62,   44,   73,   73,   63,   67,
       81,   70,   65,   68,   69,   44,   45,   45,   45,   45,
       44,   74,   74,   74,   74,   44,   74,   77,   74,   74,
       74,   74,   74,   74,   44,   44,   75,   44,   44,   44,
       44,   44,   44,   44,   44,   79,   44,   78,   44,   80,
       44,   44,   44,   88,   44,   44,   44,   84,   44,   91,
       44,   40,   82,   83,   85,   87,   86,   93,   97,   89,
       44,   44,   90,  102,   96,   99,   44,   44,   94,   44,
      100,   98,   44,   44,  101,  105,   44,   44,  104,   44,
      107,   44,   44,   44,  103,  106,   44,  114,   44,  110,

      111,   44,  108,  109,  112,  113,   44,  117,  115,  120,
       44,   44,   44,  118,   44,   44,   44,  116,  119,   44,
       44,   44,   44,   44,   44,   44,  128,  125,  126,   44,
      121,   44,  122,   44,  124,  123,  132,   44,  127,  133,
      134,   44,  129,   44,   44,   44,  131,  130,   44,   44,
      135,   44,  137,   44,   44,   44,  136,  138,  139,   44,
      141,  142,   44,  143,   44,  145,  140,  144,   44,   44,
       44,   44,   44,  155,  147,   44,  148,   44,   44,  150,
       44,   44,   44,  146,  151,   44,  149,   44,   44,  152,
       44,  158,  156,  161,  153,  154,   44,  157,   44,   44,

       44,  160,   44,  159,   44,  165,   44,  162,   44,   44,
      164,  163,   44,   44,  169,   44,   44,  166,   39,   44,
      167,  168,   44,   44,  176,  171,  170,  177,  172,  173,
      175,  178,  174,  179,  180,   44,   44,   44,   44,  184,
      185,   44,   44,   44,   38,  182,  183,  181,   44,  187,
      186,   44,   44,   44,   44,  189,   44,   44,   44,   44,
      188,   42,   42,   42,   46,   46,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   43,   71,   44,   49,   43,   37,
      190,    3,  190,  190,  190,  190,  190,  190,  190,  190,

      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190
    } ;

static yyconst flex_int16_t yy_chk[438] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   10,   23,   10,   26,   10,
       31,   25,   22,   10,   78,  197,   26,   78,   10,   21,
       10,   23,   10,   17,   17,   17,   17,   17,   22,   24,
       27,   31,   17,   18,   18,   18,   18,   18,   22,   21,
       25,   24,   27,   21,   29,   24,   28,   30,   32,   35,
       33,   34,   17,   51,   28,   27,   47,   47,   47,   30,

      196,   55,   52,   51,   29,   73,   73,   73,   29,   32,
       55,   35,   30,   33,   34,   45,   45,   45,   45,   45,
       48,   48,   48,   48,   48,   50,   48,   52,   48,   48,
       48,   48,   48,   48,   53,   56,   50,   54,   57,   58,
       61,   62,   66,   63,   67,   54,   69,   53,   70,   54,
       77,   76,   83,   66,   79,   81,   84,   58,   80,   70,
       85,  193,   56,   57,   61,   63,   62,   76,   80,   67,
       86,   87,   69,   86,   79,   83,   90,   91,   77,   93,
       84,   81,   94,   95,   85,   91,   96,   97,   90,   99,
       94,   98,  101,  105,   87,   93,  100,   99,  102,   95,

       96,  103,   94,   94,   97,   98,  106,  102,  100,  106,
      107,  108,  109,  103,  110,  111,  114,  101,  105,  116,
      112,  117,  118,  120,  119,  122,  114,  111,  112,  121,
      107,  124,  108,  126,  110,  109,  119,  127,  112,  120,
      121,  128,  116,  125,  129,  133,  118,  117,  130,  132,
      122,  131,  125,  137,  138,  139,  124,  126,  127,  141,
      129,  130,  140,  131,  143,  133,  128,  132,  144,  145,
      146,  147,  149,  147,  138,  148,  139,  150,  151,  141,
      152,  154,  155,  137,  143,  156,  140,  157,  160,  144,
      162,  150,  148,  154,  145,  146,  161,  149,  164,  163,

      165,  152,  166,  151,  168,  160,  167,  155,  170,  175,
      157,  156,  169,  171,  164,  172,  181,  161,  192,  174,
      162,  163,  182,  173,  171,  166,  165,  172,  167,  168,
      170,  173,  169,  174,  175,  176,  178,  185,  180,  181,
      182,  183,  186,  188,  191,  178,  180,  176,  189,  185,
      183,  187,  184,  179,  177,  188,  159,  158,  153,  142,
      186,  194,  194,  194,  195,  195,  136,  135,  134,  123,
      115,  113,  104,   89,   88,   82,   75,   72,   68,   65,
       64,   60,   59,   46,   42,   39,   20,   19,   11,    7,
        3,  190,  190,  190,  190,  190,  190,  190,  190,  190,

      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int pdl__flex_debug;
int pdl__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *pdl_text;
#line 1 "expr-scanner.l"
#line 4 "expr-scanner.l"
/*****************************************************************************/
/*                                                                           */
/* Copyright notice: please read file license.txt in the NetBee root folder. */
/*                                                                           */
/*****************************************************************************/



#include <stdlib.h>
#include <string.h>
#include <nbprotodb_exports.h>
#include "expressions.h"
#include "expr-grammar.tab.h"

#define YY_NO_INPUT

void pdl_error(char **, char*);


YY_BUFFER_STATE source_buffer= 0;
/* String needed for debug purposes */
char *source_buffer_string= NULL;

/* This variable is used to determine the token type from within custom code */
int TokenType;

#define YY_DECL int pdl_lex(void** lvalp)
/* #define YY_DECL int pdl_lex(YYSTYPE *lvalp) */

#line 674 "expr-scanner.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int pdl_lex_destroy (void );

int pdl_get_debug (void );

void pdl_set_debug (int debug_flag  );

YY_EXTRA_TYPE pdl_get_extra (void );

void pdl_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *pdl_get_in (void );

void pdl_set_in  (FILE * _in_str  );

FILE *pdl_get_out (void );

void pdl_set_out  (FILE * _out_str  );

yy_size_t pdl_get_leng (void );

char *pdl_get_text (void );

int pdl_get_lineno (void );

void pdl_set_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int pdl_wrap (void );
#else
extern int pdl_wrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( pdl_text, pdl_leng, 1, pdl_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( pdl_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( pdl_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, pdl_in))==0 && ferror(pdl_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(pdl_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int pdl_lex (void);

#define YY_DECL int pdl_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after pdl_text and pdl_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! pdl_in )
			pdl_in = stdin;

		if ( ! pdl_out )
			pdl_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			pdl_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				pdl__create_buffer(pdl_in,YY_BUF_SIZE );
		}

		pdl__load_buffer_state( );
		}

	{
#line 35 "expr-scanner.l"


#line 893 "expr-scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of pdl_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 191 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 392 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(ADD);   return ADD; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(SUB);   return SUB; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(MUL);   return MUL; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(DIV);   return DIV; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(MOD);   return MOD; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(BWAND); return BWAND; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(BWOR);  return BWOR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(BWNOT); return BWNOT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 46 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(EQ);    return EQ; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(NEQ);   return NEQ; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(GE);    return GE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(GT);    return GT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(LE);    return LE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 51 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(LT);    return LT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(AND);   return AND; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 53 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(OR);    return OR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 54 "expr-scanner.l"
{*lvalp= (void *) CreateOperatorItem(NOT);   return NOT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "expr-scanner.l"
{ return FUNCTION_ISASN1TYPE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "expr-scanner.l"
{ return FUNCTION_BUFFER2INT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "expr-scanner.l"
{ return FUNCTION_INT2BUFFER; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "expr-scanner.l"
{ return FUNCTION_ASCII2INT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "expr-scanner.l"
{ return FUNCTION_HASSTRING; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "expr-scanner.l"
{ return FUNCTION_EXTRACTSTRING; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "expr-scanner.l"
{ return FUNCTION_ISPRESENT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "expr-scanner.l"
{ return FUNCTION_CHANGEBYTEORDER; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "expr-scanner.l"
{ return FUNCTION_CHECKLOOKUPTABLE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "expr-scanner.l"
{ return FUNCTION_UPDATELOOKUPTABLE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "expr-scanner.l"
{ return FUNCTION_DEBUG; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "expr-scanner.l"

	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "expr-scanner.l"
{ *lvalp= (void*) CreateBooleanItem(pdl_text);		return OPERAND_BOOLEAN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "expr-scanner.l"
{ *lvalp= (void*) CreateBooleanItem(pdl_text);		return OPERAND_BOOLEAN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "expr-scanner.l"
{ *lvalp= (void*) CreateNumberItem(pdl_text, 10);    return OPERAND_NUMBER; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "expr-scanner.l"
{ *lvalp= (void *) CreateNumberItem(pdl_text+2, 16); return OPERAND_NUMBER; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "expr-scanner.l"
{ *lvalp= (void *) CreateNumberItem(pdl_text+2, 2);  return OPERAND_NUMBER; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "expr-scanner.l"
{ *lvalp= (void *) CreateVariableItem(pdl_text, &TokenType); return (TokenType); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "expr-scanner.l"
{ *lvalp= (void *) CreateLookupTableItem(pdl_text, &TokenType); return (TokenType); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 81 "expr-scanner.l"
{ *lvalp= (void *) CreateProtocolReferenceItem(pdl_text); return OPERAND_NUMBER; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "expr-scanner.l"
{ *lvalp= (void *) CreateProtoFieldItem(pdl_text); return OPERAND_PROTOFIELD; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "expr-scanner.l"
{ *lvalp= (void *) CreateProtoFieldItem(pdl_text); return OPERAND_PROTOFIELD; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 86 "expr-scanner.l"
{ *lvalp= (void *) CreateAliasItem(pdl_text, &TokenType); return (TokenType); }
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 89 "expr-scanner.l"
{
							/* Do not allocate string item here, since strings can be used also for other purposes */
							/* (e.g. as argument in hasstring() ) and in that case we do not want to create an expression */
							/* element for them. So, we duplicate only the string value in order to avoid that */
							/* 'pdl_text' gets lost. */
							*lvalp= (void *) strdup(pdl_text); return OPERAND_STRING;
						}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 "expr-scanner.l"
{ return *pdl_text; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 99 "expr-scanner.l"
{ return *pdl_text; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 100 "expr-scanner.l"
{ return *pdl_text; }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 101 "expr-scanner.l"
;       /* skip whitespace and such*/
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "expr-scanner.l"
pdl_error(NULL, "Unknown character");
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 106 "expr-scanner.l"
ECHO;
	YY_BREAK
#line 1193 "expr-scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed pdl_in at a new source and called
			 * pdl_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = pdl_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( pdl_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * pdl_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of pdl_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					pdl_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			pdl_restart(pdl_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) pdl_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 191 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 191 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 190);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					pdl_restart(pdl_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( pdl_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve pdl_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void pdl_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        pdl_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            pdl__create_buffer(pdl_in,YY_BUF_SIZE );
	}

	pdl__init_buffer(YY_CURRENT_BUFFER,input_file );
	pdl__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void pdl__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		pdl_pop_buffer_state();
	 *		pdl_push_buffer_state(new_buffer);
     */
	pdl_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	pdl__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (pdl_wrap()) processing, but the only time this flag
	 * is looked at is after pdl_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void pdl__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	pdl_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE pdl__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) pdl_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pdl__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) pdl_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in pdl__create_buffer()" );

	b->yy_is_our_buffer = 1;

	pdl__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with pdl__create_buffer()
 * 
 */
    void pdl__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		pdl_free((void *) b->yy_ch_buf  );

	pdl_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a pdl_restart() or at EOF.
 */
    static void pdl__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	pdl__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then pdl__init_buffer was _probably_
     * called from pdl_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void pdl__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		pdl__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void pdl_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	pdl_ensure_buffer_stack();

	/* This block is copied from pdl__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from pdl__switch_to_buffer. */
	pdl__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void pdl_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	pdl__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		pdl__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void pdl_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)pdl_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in pdl_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)pdl_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in pdl_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE pdl__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) pdl_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pdl__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	pdl__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to pdl_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       pdl__scan_bytes() instead.
 */
YY_BUFFER_STATE pdl__scan_string (yyconst char * yystr )
{
    
	return pdl__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to pdl_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE pdl__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) pdl_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in pdl__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = pdl__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in pdl__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pdl_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		pdl_text[pdl_leng] = (yy_hold_char); \
		(yy_c_buf_p) = pdl_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		pdl_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int pdl_get_lineno  (void)
{
        
    return pdl_lineno;
}

/** Get the input stream.
 * 
 */
FILE *pdl_get_in  (void)
{
        return pdl_in;
}

/** Get the output stream.
 * 
 */
FILE *pdl_get_out  (void)
{
        return pdl_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t pdl_get_leng  (void)
{
        return pdl_leng;
}

/** Get the current token.
 * 
 */

char *pdl_get_text  (void)
{
        return pdl_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void pdl_set_lineno (int  _line_number )
{
    
    pdl_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see pdl__switch_to_buffer
 */
void pdl_set_in (FILE *  _in_str )
{
        pdl_in = _in_str ;
}

void pdl_set_out (FILE *  _out_str )
{
        pdl_out = _out_str ;
}

int pdl_get_debug  (void)
{
        return pdl__flex_debug;
}

void pdl_set_debug (int  _bdebug )
{
        pdl__flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from pdl_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    pdl_in = stdin;
    pdl_out = stdout;
#else
    pdl_in = (FILE *) 0;
    pdl_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * pdl_lex_init()
     */
    return 0;
}

/* pdl_lex_destroy is for both reentrant and non-reentrant scanners. */
int pdl_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		pdl__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		pdl_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	pdl_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * pdl_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *pdl_alloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *pdl_realloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void pdl_free (void * ptr )
{
			free( (char *) ptr );	/* see pdl_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 106 "expr-scanner.l"




int pdl_wrap(void)
{
    return 1;
}

void protodb_lex_init(const char * buffer)
{
	source_buffer_string= (char*) buffer;
	source_buffer= pdl__scan_string(buffer);
}


void protodb_lex_cleanup()
{
	if (source_buffer)
		pdl__delete_buffer(source_buffer);
	source_buffer= 0;
}


